### PR TITLE
Simple addition to renderer

### PR DESCRIPTION
**Pull request by krall2125**
A simple addition to the renderer which if I am not mistaken, should create a box and load various things into matrices for the shader to use. The actual drawing and vertex arrays are still not implemented, so the renderer is not functional.

### CODE REVIEW

**Comment by hellory4n** [comment]
forgot to merge this lmao

**Comment by krall2125** [comment]
True...

**Comment by hellory4n** [comment]
i forgor again 🤔🔥🤮➡️🤔🟥🤓⭐🤑🔴🔴🤑🤣🤔⬆️⬆️😇😂😊😊😊🤮🤔🔥🤮➡️🤔🟥🤓⭐🤑🔴🔴🤑🤣🤔⬆️⬆️😇😂😊😊😊🤮🤔🔥🤮➡️🤔🟥🤓⭐🤑🔴🔴🤑🤣🤔⬆️⬆️😇😂😊😊😊🤮🤔🔥🤮➡️🤔🟥🤓⭐🤑🔴🔴🤑🤣🤔⬆️⬆️😇😂😊😊😊🤮🤔🔥🤮➡️🤔🟥🤓⭐🤑🔴🔴🤑🤣🤔⬆️⬆️😇😂😊😊😊🤮🤔🔥🤮➡️🤔🟥🤓⭐🤑🔴🔴🤑🤣🤔⬆️⬆️😇😂😊😊😊🤮

**Comment by krall2125** [comment]
epic

**Pull request merged**
